services:
  - type: web
    name: joblo-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-build-isolation --prefer-binary -r requirements.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port 10000
build:
  pythonVersion: 3.10
